#aws configure --profile="souqProfile" -> enter "accessKeyId" and "secertAccessKey" and region "ap-south-1"
#pipenv install boto3
#pipenv run python souqMigrator.py

import boto3
import json

class ReceiveData:
    def __init__(self, asin, fnsku, iog, glProductGroupId):
        self.asin = asin
        self.fnsku = fnsku
        self.iog = iog
        self.glProductGroupId = glProductGroupId

#Connecting to S3
session = boto3.Session(profile_name='souqProfile')
s3 = session.resource('s3')
bucketName="souqtest"


#Get Master Data generated by shipment team
masterDataObject = s3.Object(bucketName, '02-11/shipment/masterShipmentRetail.json')
masterDataText = masterDataObject.get()['Body'].read().decode('utf-8')
masterDataDictList = json.loads(masterDataText)


#Generate and print Hash map of Master Data
masterDataHashMap = {}
for masterDataDict in masterDataDictList:
    masterDataHashMap[masterDataDict['SouqSku']] = ReceiveData(masterDataDict['Asin'], masterDataDict['FnSKU'], masterDataDict['IOG'], masterDataDict['GLProductGroupID'])

print("Master data hash Map")
for key in masterDataHashMap:
    print ("{} -> {}".format(key,masterDataHashMap[key].__dict__))


#Get Souq data in memory
souqDataObject = s3.Object(bucketName, '02-11/souq/souqAddRetail.json')
souqDataText = souqDataObject.get()['Body'].read().decode('utf-8')
souqDataDictList = json.loads(souqDataText)


#Start receive Souq data by performing look-up in the Master Hash map
souqDataDictListSuccess =[]
souqDataDictListFailure =[]
for souqDataDict in souqDataDictList:
    if(masterDataHashMap.get(souqDataDict['SouqSku'],None) != None):
        souqDataDictListSuccess.append(souqDataDict)
    else:
        souqDataDictListFailure.append(souqDataDict)


#Generate Receive Success file
print("\n\nSuccess records -")
print(souqDataDictListSuccess)
receiveSuccessFileName = "successReceiveRetail.json"
s3KeyForSuccess="02-11/receive/{}".format(receiveSuccessFileName)
with open(receiveSuccessFileName, 'w') as f:
    json.dump(souqDataDictListSuccess, f)


#Generate Receive Failure file
print("\n\nFailure records -")
print(souqDataDictListFailure)
receiveFailureFileName = "failureReceiveRetail.json"
s3KeyForFailure="02-11/receive/{}".format(receiveFailureFileName)
with open("failureReceiveRetail.json", 'w') as f:
    json.dump(souqDataDictListFailure, f)


#Upload Receive Success file to S3
print("\n\nUploading success file...")
s3.meta.client.upload_file(receiveSuccessFileName, bucketName, s3KeyForSuccess, ExtraArgs={'ContentType': 'text/plain'})
print("DONE")


#Upload Receive Failure file to S3
print("\n\nUploading failure file...")
s3.meta.client.upload_file(receiveFailureFileName, bucketName, s3KeyForFailure, ExtraArgs={'ContentType': 'text/plain'})
print("DONE")
